{{ range $secret := $.Values.controlPlane.additionalK8sSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $secret.name $ | quote }}
  labels: {{ include "kuma.cpLabels" $ | nindent 4 }}
stringData:
  {{ range $key, $value := $secret.stringData }}
  {{ $key | quote }}: {{ $value | quote }}
  {{ end }}
{{ end }}
