{{ if .Values.controlPlane.kdsZoneClientTLSSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuma.name" . }}-kds-zone-client-tls
  labels: {{ include "kuma.cpLabels" . | nindent 4 }}
stringData:
  ca.crt: {{ .Values.controlPlane.kdsZoneClientTLSSecret.cert | quote }}
{{ end }}
