{{ if .Values.controlPlane.kdsGlobalServerTLSSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuma.name" . }}-kds-global-server-tls
  labels: {{ include "kuma.cpLabels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.controlPlane.kdsGlobalServerTLSSecret.cert | quote }}
  tls.key: {{ .Values.controlPlane.kdsGlobalServerTLSSecret.key | quote }}
{{ end }}
