{{ if .Values.controlPlane.kdsGlobalServerTLSSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuma.name" . }}-kds-global-server-tls
  labels:
    {{- include "kuma.labels" . | nindent 4 }}
    app: {{ include "kuma.name" . }}-control-plane
    {{ range $key, $value := .Values.controlPlane.extraLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{ end }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.controlPlane.kdsGlobalServerTLSSecret.cert | quote }}
  tls.key: {{ .Values.controlPlane.kdsGlobalServerTLSSecret.key | quote }}
{{ end }}
