{{ if .Values.controlPlane.kdsZoneClientTLSSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuma.name" . }}-kds-zone-client-tls
  labels:
    {{- include "kuma.labels" . | nindent 4 }}
    app: {{ include "kuma.name" . }}-control-plane
    {{ range $key, $value := .Values.controlPlane.extraLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{ end }}
stringData:
  ca.crt: {{ .Values.controlPlane.kdsZoneClientTLSSecret.cert | quote }}
{{ end }}
