{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuma.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kuma.labels" . | nindent 4 }}
    {{ range $key, $value := .Values.ingress.extraLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{ end }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
